services:
  frontend:
    build: ./frontend
    ports:
      - '3000:80'
    networks:
      - formnet

  backend:
    build: ./backend
    ports:
      - '4000:4000'
    environment:
      - PORT=4000
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/form_builder
    depends_on:
      - postgres
    networks:
      - formnet

  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: form_builder
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - formnet

volumes:
  pgdata: {}

networks:
  formnet:
    driver: bridge
