version: '3.9'
services:
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - '3000:3000'
  # backend:
  #   build: ./backend
  #   ports:
  #     - '4000:4000'
  #   depends_on:
  #     - postgres
  # postgres:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: form_builder
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
